### Exercise 1

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.   
Expected Output:

```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
```

In [2]:
import numpy as np

In [4]:
# Create a 3x3 matrix with values 2 to 10 using reshape instead of manual lists.
import numpy as np 

# Generate range and reshape immediately
matrix_3x3 = np.arange(2, 11).reshape(3, 3)
print(matrix_3x3)



[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Exercise 2

Write a NumPy program to create a new array of 3*5, filled with 2.   

Expected Output:

```
array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])
```


In [5]:
 
#  Create ones and multiply by 2.
arr_3x5_alt = np.ones((3, 5), dtype=int) * 2
print(repr(arr_3x5_alt))



array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])


### Exercise 3

Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.  
Expected output:
```
array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])
```

In [6]:

#Use broadcasting or tile with float conversion inline.
row_vals = np.arange(5).astype(float)
arr_5x5_alt = np.tile(row_vals, (5, 1))
print(repr(arr_5x5_alt))



array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])


### Exercise 4
Write a NumPy program to reverse an array (first element becomes last).  

* Original array:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]  
* Reverse array:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [7]:
# Reverse an array.
# Logic remains slicing, but let's define the range dynamically.
start_val, end_val = 12, 38
orig_arr = np.arange(start_val, end_val)
# Slicing with step -1 reverses it
rev_arr = orig_arr[::-1]

print(f"Original: {orig_arr}")
print(f"Reversed: {rev_arr}")



Original: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


### Exercise 5
Write a NumPy program to create a 1D array containing 20 random integers between 1 and 6 (included).  
Next filter this array to a new one containing only the odd numbers.

In [8]:
# Random integers 1-6, filter odds.
# Setting a seed ensures reproducibility if needed, but let's just generate.
random_data = np.random.randint(low=1, high=7, size=20)
# Filter: Keep where remainder of division by 2 is 1
odd_filter = random_data % 2 == 1
only_odds = random_data[odd_filter]

print(f"Source: {random_data}")
print(f"Filtered Odds: {only_odds}")



Source: [4 1 6 6 1 3 1 6 6 2 6 3 5 6 4 5 5 4 3 1]
Filtered Odds: [1 1 3 1 3 5 5 5 3 1]


### Exercise 6
Write a NumPy program to get the positions where elements of a and b match  

Input:  
```
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])  
```

Expected Output:  
```
(array([1, 3, 5, 7]),)
```

In [9]:

# Find matching indices between two arrays.
vec_a = np.array([1,2,3,2,3,4,3,4,5,6]) 
vec_b = np.array([7,2,10,2,7,4,9,4,9,8]) 
# np.where returns a tuple, we just print it
match_indices = np.where(vec_a == vec_b)
print(match_indices)


(array([1, 3, 5, 7], dtype=int64),)


### Exercise 7
 Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.   
Checkerboard pattern:  
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
 ```

In [10]:
# Checkerboard pattern.
# Alternative logic: Initialize with zeros, then set specific slices to 1.
board = np.zeros((8, 8), dtype=int)
# Set odd rows, even columns to 1
board[1::2, ::2] = 1
# Set even rows, odd columns to 1
board[::2, 1::2] = 1
print(board)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Exercise 8
 Write a NumPy program to create a 4x4 matrix.  
 Original array:

```
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]
[12 13 14 15]]  
```

* Extract all the elements of the first and fourth rows.  
Expected output:

```
[[ 0,  1,  2,  3], [12, 13, 14, 15]]
```

* Extract all the elements of the first and fourth columns.  
Expected output :

```
[[ 0 3]
[ 4 7]
[ 8 11]
[12 15]]
```

* Extract second and third elements of the second and third rows  
Expected output:

```
[[ 5 6]
[ 9 10]]
```

In [11]:
# Matrix slicing exercises.
base_mat = np.arange(16).reshape(4, 4)

# 1. First and last rows (using negative indexing for clarity)
rows_extract = base_mat[[0, -1]]
print("Rows 1 & 4:\n", rows_extract)

# 2. First and last columns
cols_extract = base_mat[:, [0, -1]]
print("Cols 1 & 4:\n", cols_extract)

# 3. Inner 2x2 square (rows 1-2, cols 1-2)
inner_square = base_mat[1:3, 1:3]
print("Inner Square:\n", inner_square)



Rows 1 & 4:
 [[ 0  1  2  3]
 [12 13 14 15]]
Cols 1 & 4:
 [[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]
Inner Square:
 [[ 5  6]
 [ 9 10]]


### Exercise 9
Import a dataset with numbers and texts _keeping the text intact_ in a python NumPy array.

The dataset can be found on this url: [https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).  

The data is also available as iris.csv in the files folder.

Each row consists of 5 fields:
* 'sepallength': number
* 'sepalwidth': number
* 'petallength': number
* 'petalwidth': number
* 'species': text

To load this dataset you need to use the genfromtxt() function and make sure that dtype is set to object. Otherwise the 'species' field will contain NaN values.  

Expected output (first 3 rows)
```
array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)
```

In [12]:

# Load Iris data with text.
# Using local file path as per previous context, ensuring dtype object.
iris_raw = np.genfromtxt('files/iris.csv', delimiter=',', dtype='object', skip_header=1)
print(iris_raw[:3])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'setosa']]


### Exercise 10
Import the iris dataset again but now just the first four columns.  
Check if there are any missing values in the sepallength (1st column).  
This can be done with the function isnan()  

Expected output:  
Number of missing values: 0  
Position of missing values:
```
(array([], dtype=int64),)
```

Use the commented code in the first block to introduce some missing values. This will help you make sure your code works.

In [ ]:
# initialisation
#url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#iris_numbers = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

## If the URL doesn't work
iris_numbers = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, encoding=None, skip_header=1,usecols=[0,1,2,3])

iris_numbers[1,2] = np.nan
iris_numbers[2,2] = np.nan

In [13]:

# Check for NaNs in sepallength.
# Loading only numeric columns.
iris_nums = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, skip_header=1, usecols=(0,1,2,3))

# Intentionally injecting NaNs to test logic (as per original instructions)
iris_nums[1, 0] = np.nan 
iris_nums[4, 0] = np.nan 

col_0 = iris_nums[:, 0]
is_missing = np.isnan(col_0)

count_missing = np.sum(is_missing)
locs_missing = np.where(is_missing)

print(f"Missing count: {count_missing}")
print(f"Locations: {locs_missing}")


Missing count: 2
Locations: (array([1, 4], dtype=int64),)


### Exercise 11
Compute the mean, median, standard deviation of iris's sepallength (1st column)  

Expected output:  
```
mean: 5.843333333333334   
median: 5.8   
standard deviation: 0.8253012917851409  
```

In [14]:

# Stats for sepallength (ignoring the injected NaNs from ex 10 by reloading clean or handling them).
# Let's reload clean for accurate stats.
clean_sepals = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, skip_header=1, usecols=0)

avg = np.mean(clean_sepals)
mid = np.median(clean_sepals)
spread = np.std(clean_sepals)

print(f"Mean: {avg}")
print(f"Median: {mid}")
print(f"Std Dev: {spread}")



Mean: 5.843333333333334
Median: 5.8
Std Dev: 0.8253012917851409


### Exercise 12
Find the 5th and 95th percentile of iris's sepallength.  (1st column)  

Expected output:
```
array([4.6  , 7.255])
```

In [15]:
# Percentiles.
p_5_95 = np.percentile(clean_sepals, [5, 95])
print(repr(p_5_95))



array([4.6  , 7.255])


### Exercise 13
Filter the rows in the iris data array that haves petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0  
The resulting array contains the 4 numeric fields for each retrieved row.  

Expected output: 
``` 
array([[4.8, 3.4, 1.6, 0.2],  
       [4.8, 3.4, 1.9, 0.2],  
       [4.7, 3.2, 1.6, 0.2],  
       [4.8, 3.1, 1.6, 0.2],  
       [4.9, 2.4, 3.3, 1. ],  
       [4.9, 2.5, 4.5, 1.7]])
```


In [16]:
# Complex filtering: Petal > 1.5 AND Sepal < 5.0
data_all = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, skip_header=1, usecols=(0,1,2,3))

# Mask creation
mask_petal = data_all[:, 2] > 1.5
mask_sepal = data_all[:, 0] < 5.0

# Combine masks
final_mask = mask_petal & mask_sepal
filtered_data = data_all[final_mask]

print(repr(filtered_data))



array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])
